# [Tensors](https://pytorch.org/tutorials/beginner/basics/tensor_tutorial.html)

**Tensors** are like arrays and matrices. They encode inputs, outputs, and parameters of the model.

In [1]:
import torch
import numpy as np

We can create Tensor objects from Python and Numpy arrays

In [5]:
data = [
    [1, 2],
    [3, 4]
]
print("data", type(data))
x_data = torch.tensor(data)
print("x_data", type(x_data))

data <class 'list'>
x_data <class 'torch.Tensor'>


In [6]:
np_array = np.array(data)
print("np_array", type(np_array))
x_np = torch.from_numpy(np_array)
print("x_np", type(x_np))

np_array <class 'numpy.ndarray'>
x_np <class 'torch.Tensor'>


We can create Tensors that retain the properties (shape, datatype) of the original Tensor. We can retain or override the properties.

In [10]:
x_ones = torch.ones_like(x_data)
print("Ones Tensor")
print(x_ones)

Ones Tensor
tensor([[1, 1],
        [1, 1]])


In [14]:
# Change the Tensor contents and convert the datatype from integer to float
x_rand = torch.rand_like(x_data, dtype=float)
print("Random Tensor")
print(x_rand)

Random Tensor
tensor([[0.7347, 0.9293],
        [0.2903, 0.3051]], dtype=torch.float64)


We can use a tuple to define the Tensor's shape

In [19]:
shape = (3,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor\n", rand_tensor)
print("Ones Tensor\n", ones_tensor)
print("Zeros Tensor\n", zeros_tensor)

Random Tensor
 tensor([[0.3868, 0.6128],
        [0.4874, 0.8182],
        [0.8620, 0.1196]])
Ones Tensor
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
Zeros Tensor
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


We can print the attributes of a Tensor

In [47]:
tensor = torch.randint(low=0, high=10, size=(2,3))
print(tensor)
print("Shape: ", tensor.shape)
print("Datatype: ", tensor.dtype)
# The device where the Tensor is stored at
print("Device: ", tensor.device)

tensor([[2, 2, 1],
        [5, 6, 2]])
Shape:  torch.Size([2, 3])
Datatype:  torch.int64
Device:  cpu


## Operations on Tensors
If a GPU is available, we can copy the Tensor to a GPU

In [48]:
print("GPU available: ", torch.cuda.is_available())

GPU available:  False


In [49]:
print("Is Tensor: ", torch.is_tensor(tensor))

Is Tensor:  True


In [50]:
print(torch.max(tensor))

tensor(6)


In [51]:
# Returns a new Tensor where cosine of every element is taken in the original
torch.cos(tensor)

tensor([[-0.4161, -0.4161,  0.5403],
        [ 0.2837,  0.9602, -0.4161]])

In [52]:
# Combine tensors
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[2, 2, 1, 2, 2, 1],
        [5, 6, 2, 5, 6, 2]])

In [53]:
# Matrix multiplication
# Can also use matrix.matmul()
y1 = tensor @ tensor.T
y1

tensor([[ 9, 24],
        [24, 65]])

In [54]:
# Element-wise multiplication
y2 = tensor * tensor
y2

tensor([[ 4,  4,  1],
        [25, 36,  4]])

In [55]:
# Convert the value of a single-element Tensor into a Python numerical value
agg = tensor.sum()
print(agg)
print(agg.item())

tensor(18)
18


In [57]:
# In-place operators are denoted by the suffix `_`
print(tensor)
tensor.add_(1)

tensor([[2, 2, 1],
        [5, 6, 2]])


tensor([[3, 3, 2],
        [6, 7, 3]])

## Bridge with Numpy
Tensors and Numpy arrays can share their memory locations. Modifying one will update the other.

In [64]:
t = torch.ones(3)
print("Tensor", t)
n = t.numpy()
print("Numpy", n)

Tensor tensor([1., 1., 1.])
Numpy [1. 1. 1.]


In [65]:
t.add_(1)
print("Tensor", t)
print("Numpy", n)

Tensor tensor([2., 2., 2.])
Numpy [2. 2. 2.]
